version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"  # expose Nginx to host
    volumes:
      - ./backend:/app/backend
      - ./client:/app/client
      - db_data:/app/backend/db.sqlite3
    restart: always

volumes:
  db_data:
