version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./client:/app/client
      - db_data:/app/backend/db.sqlite3
    command: gunicorn website.wsgi:application --bind 0.0.0.0:8000

volumes:
  db_data:
