# Generated by Django 5.2.4 on 2025-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_ticketscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_url',
            field=models.URLField(max_length=500),
        ),
    ]
